kind: Deployment
apiVersion: apps/v1
metadata:
  name: notes-app-deployment
  namespace: nginx
  labels:
    app: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      name: notes-app-dep-pod
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app
        image: kuldeepsharmaks1/notes-app-k8s
        ports:
          - containerPort: 8000
